#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-storage-file - lab script for DO380-OCP4
#
# SYNOPSIS
#     lab-storage-file {start|finish}
#
#        start  - prepare the system for starting the lab
#        finish - perform post-lab finish
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the [name of the exercise]
#
# CHANGELOG
#   * Mod Jun 1 Dan Kolepp <dkolepp@redhat.com>
#   - initial creation


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/root/bin:/usr/local/bin
declare -a valid_commands=(start finish)

# Change these variables to match your exercise
this='storage-block'
title='Guided Exercise: Provisioning Block Storage for Databases'

# Do not change these variables
target='workstation'
run_as_root='true'


function lab_start {

  ocp4_print_prereq_header

  ocp4_is_cluster_up
  # For this GE in particular, a default storage class is disabled.
  # Typically, for other GEs, set this to "true"

  # TODO: Toggle below two lines after default storage class name is changed.
  ocp4_set_default_storageclass nfs-storage true
  print_line
  ocp4_fail_if_project_exists "${this}"
  ocp4_exit_on_failure "It looks like you have already started this exercise. To try this exercise again, run 'lab ${this} finish' followed by 'lab ${this} start'."

  ocp4_print_setup_header

  print_line
  print_line " Preparing the student's cluster:"
  ocp4_grab_lab_files

  ocp4_print_setup_footer
}


function lab_finish {

  ocp4_print_cleanup_header

  ocp4_login_as_admin
  ocp4_set_default_storageclass nfs-storage "true"
  ocp4_delete_project "${this}"
  ocp4_cleanup_lab_files

  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
