apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-01
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: iscsi-blk
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 172.25.250.253:3260
     iqn: iqn.2020-06.com.example:utility.lab.example.com
     lun: 1
     initiatorName: iqn.2020-06.com.example:openshift
     fsType: 'ext4'
     readOnly: false
